### ISSUE TITLE
y7000p-2018 使用，内置键盘不生效、开机亮度没有保持上次配置

### ISSUE THREAD

**Issue by iamxiyang** [1orz/y7000p-2020H-macOS-EFI#1]
首先感谢作者提供的EFI，我在y7000p系列2018款上使用了这款EFI，目前看使用正常，但发现了2点小问题：

1、内置键盘不生效、任何键点击都没效果，但外接键盘可以正常使用。

2、开机后亮度比较暗，我手动修改了屏幕亮度，后续每次开机都还是保持相同的亮度（即比较暗的情况），没有保持我使用时设置的亮度。

不知道作者有没有遇到这两个问题，有没有计划进行修复？

系统：mac12.5.1
设备：y7000p-2018

**Comment by 1orz** [comment]
1.对于键盘问题。本机为2020款拯救者。暂未遇到过c面键盘不工作问题。键盘多采用I2C。你可以根据自己的实际硬件情况。重新手动编译生成ACPI 的I2C部分。覆盖SSDT-I2C
2.对于亮度问题，本机也未发生亮度调节失效的问题。对于2018来说。猜测依旧是硬件上的差别导致亮度调节数据无法存储。试试看看ACPI部分SSDT-PNLF重新编译并替换？另外。二者的CPU不同。很对地方差异会更大。如果是为了完美适配。建议从头阅读[这篇文档](https://dortania.github.io/OpenCore-Install-Guide/)。

由于没有对应机型。无法进行实测。所有解决方案均依赖主观经验猜测。建议多阅读文档

**Comment by iamxiyang** [comment]
我看到另一款EFI中提到笔记本内置键盘失灵修复的方案，是需要做 VoodooPS2Controller 和 VoodooI2C 的调整。

https://github.com/MakiNaruto/Hackintosh-LEGION-Y7000P-I7-8750H#%E4%BF%AE%E5%A4%8D%E8%AE%B0%E5%BD%95

**Comment by iamxiyang** [comment]
> 由于没有对应机型。无法进行实测。所有解决方案均依赖主观经验猜测。建议多阅读文档

我先阅读一下文档，抽空尝试看看
